application: x-again
version: uni
runtime: python
api_version: 1

handlers:
## Favion url.
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon

## admin_console
- url: /admin_console/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

## Appstats
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  secure: always
  login: admin

## Main WSGI
- url: .*
  script: main.py
  secure: always
  login: admin

admin_console:
  pages:
  - url: /stats
    name: "Appstats"
  - url: /admin_console/
    name: "Admin_console"
